spring.application.name=comentoStatistic

server.port = 8031
server.servlet.contextPath =/

logging.level.org.springframework.web = DEBUG
logging.level.org.hibernate = ERROR

devtools.livereload.enabled = true

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/statistic
spring.datasource.username=root
spring.datasource.password=0000


# Mybatis mapper ?? ??
mybatis.mapper-locations= classpath:mapper/*.xml

## xml?? result type? ????? ??? ? ??? alias ??
mybatis.type-aliases-package=com.demo.comentoStatistic.dto

holiday.api.service-key=c23a0a60159dcf9f65ed03a98d0229cde808662cb2517b9428d212fdff01726c
holiday.api.url=http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo